project:
  type: website
  output-dir: docs

website:
  title: "Victoria Yang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Resume.pdf
        text: Resume
    background: light
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Victoria Yang"
    right: 
      - icon: github
        href: https://github.com/v-yc

format:
  html:
    theme: [morph, mystyles.scss]
    css: styles.css
    toc: true
    page-layout: full

editor: visual

